// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbDj89RJ4P9B1lttoO4MeIH4vhMllgjW4',
    appId: '1:574641368519:web:a6a6b813fc999669b8bde2',
    messagingSenderId: '574641368519',
    projectId: 'flutter-todo-app-61b7a',
    authDomain: 'flutter-todo-app-61b7a.firebaseapp.com',
    storageBucket: 'flutter-todo-app-61b7a.firebasestorage.app',
    measurementId: 'G-GH5FY5XFDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYwHN_hEUgNsoQfcBIt--SYvCJDvqn2Nw',
    appId: '1:574641368519:android:a56384c6521217ceb8bde2',
    messagingSenderId: '574641368519',
    projectId: 'flutter-todo-app-61b7a',
    storageBucket: 'flutter-todo-app-61b7a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbDj89RJ4P9B1lttoO4MeIH4vhMllgjW4',
    appId: '1:574641368519:web:93af1b0ac172908cb8bde2',
    messagingSenderId: '574641368519',
    projectId: 'flutter-todo-app-61b7a',
    authDomain: 'flutter-todo-app-61b7a.firebaseapp.com',
    storageBucket: 'flutter-todo-app-61b7a.firebasestorage.app',
    measurementId: 'G-VSWPD4J66K',
  );
}
